/**
 * Service Worker for "Upright Condensing Precision Clock"
 * Generated by PWA Forge
 * Cache Version: v1.0.0
 *
 * Features:
 *   - Precaching of static assets
 *   - Smart dynamic caching (network-first for HTML, cache-first for assets)
 *   - Offline fallback page
 *   - Cache versioning and automatic cleanup
 *   - Background sync support
 */

'use strict';

const CACHE_NAME   = 'pwa-forge-v1.0.0';
const STATIC_CACHE = 'static-v1.0.0';
const DYNAMIC_CACHE= 'dynamic-v1.0.0';
const MAX_DYNAMIC_CACHE_ITEMS = 50;

/** Static assets to precache on install */
const STATIC_ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './offline.html',
  './192x192.png',
  './512x512.png',

];

/** Patterns that should NEVER be cached */
const NEVER_CACHE = [
  /chrome-extension/,
  /extension/,
  /\.map$/,
  /socket\.io/,
  /hot-update/,
  /localhost:\d{4,5}\/sockjs/,
];

/* ── UTILITY ────────────────────────────────── */

/** Trim dynamic cache to MAX_DYNAMIC_CACHE_ITEMS */
async function trimCache(cacheName, maxItems) {
  try {
    const cache = await caches.open(cacheName);
    const keys  = await cache.keys();
    if (keys.length > maxItems) {
      const toDelete = keys.slice(0, keys.length - maxItems);
      await Promise.all(toDelete.map(k => cache.delete(k)));
    }
  } catch(e) { console.warn('[SW] trimCache error:', e); }
}

/** Check if a request should be cached */
function isCacheable(request) {
  if (request.method !== 'GET') return false;
  const url = new URL(request.url);
  if (url.protocol !== 'https:' && url.hostname !== 'localhost') return false;
  return !NEVER_CACHE.some(p => p.test(request.url));
}

/* ── INSTALL EVENT ──────────────────────────── */
self.addEventListener('install', event => {
  console.log('[SW] Installing v1.0.0...');
  event.waitUntil(
    caches.open(STATIC_CACHE)
      .then(cache => {
        // Add assets one-by-one to avoid total failure if one asset 404s
        const promises = STATIC_ASSETS.map(url =>
          cache.add(url).catch(err => {
            console.warn('[SW] Failed to cache:', url, err.message);
          })
        );
        return Promise.all(promises);
      })
      .then(() => {
        console.log('[SW] Install complete.');
        return self.skipWaiting(); // Activate immediately
      })
      .catch(err => console.error('[SW] Install failed:', err))
  );
});

/* ── ACTIVATE EVENT ─────────────────────────── */
self.addEventListener('activate', event => {
  console.log('[SW] Activating v1.0.0...');
  event.waitUntil(
    caches.keys()
      .then(cacheNames => {
        const validCaches = [STATIC_CACHE, DYNAMIC_CACHE];
        const toDelete = cacheNames.filter(name => !validCaches.includes(name));
        return Promise.all(toDelete.map(name => {
          console.log('[SW] Deleting stale cache:', name);
          return caches.delete(name);
        }));
      })
      .then(() => {
        console.log('[SW] Activate complete.');
        return self.clients.claim(); // Take control of all clients
      })
  );
});

/* ── FETCH EVENT ────────────────────────────── */
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);

  // Skip non-GET and non-cacheable requests
  if (!isCacheable(request)) return;

  // Navigation requests: Network-First with offline fallback
  if (request.mode === 'navigate' || request.headers.get('accept')?.includes('text/html')) {
    event.respondWith(handleNavigationRequest(request));
    return;
  }

  // Static assets (CSS, JS, images, fonts): Cache-First
  if (isStaticAsset(request.url)) {
    event.respondWith(handleStaticAsset(request));
    return;
  }

  // API / dynamic requests: Network-First with dynamic cache fallback
  event.respondWith(handleDynamicRequest(request));
});

/** Network-First strategy for HTML pages */
async function handleNavigationRequest(request) {
  try {
    const networkResponse = await fetchWithTimeout(request, 8000);
    if (networkResponse && networkResponse.ok) {
      const cache = await caches.open(DYNAMIC_CACHE);
      cache.put(request, networkResponse.clone());
    }
    return networkResponse;
  } catch(err) {
    console.warn('[SW] Navigation fetch failed, trying cache:', err.message);
    const cached = await caches.match(request);
    if (cached) return cached;
    // Return the offline fallback page
    return caches.match('./offline.html') || generateOfflineResponse();
  }
}

/** Cache-First strategy for static assets */
async function handleStaticAsset(request) {
  const cached = await caches.match(request);
  if (cached) return cached;

  try {
    const networkResponse = await fetch(request);
    if (networkResponse && networkResponse.ok) {
      const cache = await caches.open(STATIC_CACHE);
      cache.put(request, networkResponse.clone());
    }
    return networkResponse;
  } catch(err) {
    console.warn('[SW] Static asset fetch failed:', request.url);
    return new Response('Asset unavailable offline', { status: 503 });
  }
}

/** Network-First with dynamic cache */
async function handleDynamicRequest(request) {
  try {
    const networkResponse = await fetchWithTimeout(request, 5000);
    if (networkResponse && networkResponse.ok) {
      const cache = await caches.open(DYNAMIC_CACHE);
      cache.put(request, networkResponse.clone());
      await trimCache(DYNAMIC_CACHE, MAX_DYNAMIC_CACHE_ITEMS);
    }
    return networkResponse;
  } catch(err) {
    const cached = await caches.match(request);
    if (cached) return cached;
    return new Response(JSON.stringify({ error: 'Offline', message: 'No cached version available.' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}

/** Check if URL is a static asset */
function isStaticAsset(url) {
  return /\.(css|js|png|jpg|jpeg|gif|webp|svg|ico|woff2?|ttf|eot|otf|mp4|mp3|wav)$/i.test(url);
}

/** Fetch with timeout */
function fetchWithTimeout(request, ms) {
  const controller = new AbortController();
  const timeout    = setTimeout(() => controller.abort(), ms);
  return fetch(request, { signal: controller.signal })
    .finally(() => clearTimeout(timeout));
}

/** Minimal offline response when even offline.html is not cached */
function generateOfflineResponse() {
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Offline</title>
  <style>body{font-family:sans-serif;text-align:center;padding:60px;background:#111;color:#eee;}
  h1{color:#00d4aa;}p{color:#888;}</style></head>
  <body><h1>📡 You're Offline</h1><p>Please check your connection and try again.</p></body></html>`;
  return new Response(html, { status: 200, headers: { 'Content-Type': 'text/html' } });
}

/* ── MESSAGE HANDLER ────────────────────────── */
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  if (event.data && event.data.type === 'GET_VERSION') {
    event.ports[0].postMessage({ version: CACHE_NAME });
  }
});

console.log('[SW] Script loaded: ' + CACHE_NAME);
